### ISSUE TITLE
READMEに有益な情報が載っていない

### ISSUE THREAD

**Issue by tamanobi** [taiseiyo/computational_game#4]
とあるスキャフォールドのテンプレートのままになっているので修正して欲しい。

ゲームの概要や、コンポーネントの構成、コントリビュートするための方法を書いておくと親切。

**Comment by taiseiyo** [comment]
コメントありがとうございます。

質問なのですが、私は基本 README は org ファイルで作成を行っていますが、
md ファイルと org ファイルが混在している場合は md ファイルが優先されて表示されてしまいます。
これについて org ファイルを優先して表示する事はできるのでしょうか。

**Comment by tamanobi** [comment]
README.org のみ残してREADME.md を削除すれば問題ないと思います。
http://yasuyk.github.io/blog/2013/04/27/github-readme-org-mode/
