### ISSUE TITLE
node_modulesの中身がpushされている

### ISSUE THREAD

**Issue by tamanobi** [taiseiyo/computational_game#5]
package-lock.json があるので、node_modulesは必要ない

https://qiita.com/fj_yohei/items/7ca887a45e0855917279

**Comment by taiseiyo** [comment]
コメントありがとうございます！！

リンク先の資料読ませて頂きました。
その上でまだ以下の疑問が残っているのでお答えして頂けないでしょうか。

- package-lock.json の中に依存関係が記されているのは理解しましたが、実際使用するモジュールの集合である node_module がないのにローカル環境で動かす事が可能なのか？

**Comment by tamanobi** [comment]
原則としてGitリポジトリには成果物はコミットしません。なぜなら成果物が変わったときのコミット忘れ、成果物によるリポジトリ肥大に伴うコミット時間の増大、環境による成果物の差異がGitで吸収できないことなど、数多のデメリットが挙げられるからです。これらのデメリットは Git がスナップショットで変更を追従していることが原因です。

package-lock.json があれば、`npm i` にてnode_modules を復元できますので心配は無用です。

**Comment by taiseiyo** [comment]
懇切丁寧なコメントありがとうございました！
